# Define the trigger for the pipeline


trigger:
 - main

# Define the agent pool
pool:
  name: 'my-personal-computer'

stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: "1.0"
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True
    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: '**/*.sln'
        feedsToUse: 'config'
        nugetConfigPath: 'nuget.config'

    - task: VSBuild@1
      inputs:
        solution: '**/*.sln'
        msbuildArgs: '/p:Configuration=Release'
        platform: 'Any CPU'
        configuration: 'Release'

    - task: PowerShell@2
      displayName: 'Set Execution Policy'
      inputs:
        targetType: inline
        script: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

    - task: PowerShell@2
      displayName: 'Reading Settings'
      inputs:
        targetType: filePath
        filePath: 'C:\Users\Legion 5 Pro\Desktop\AzureDevops\Shell\Old.HelloWorld-master\scripts\Read-Settings.ps1'
        arguments: '-appVersion "$(appVersion).$(appBuild).$(appRevision)"'
        failOnStderr: true

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'drop'

   
  
