# Define the trigger for the pipeline
trigger:
- main

# Define the agent pool
pool:
  name: 'my-personal-computer'

# Define stages
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: "1.0"
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True
    steps:

    - task: PowerShell@2
      displayName: 'Set Execution Policy'
      inputs:
        targetType: inline
        script: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: '$(Build.ArtifactStagingDirectory)'
        artifactName: 'MyProject'
