# Define the trigger for the pipeline


trigger:
 - main

# Define the agent pool
pool:
  name: 'my-personal-computer'

# Define stages
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: "1.0"
      appBuild: $[counter(variables['appVersion'],0)]
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True

 

    steps:
    - task: PowerShell@2
      displayName: 'Reading Settings'
      inputs:
        targetType: filePath
        filePath: 'C:\Users\Legion 5 Pro\Desktop\AzureDevops\Shell\Old.HelloWorld-master\scripts'
        arguments: '-appVersion "$(appVersion).$(appBuild).$(appRevision)"'
        failOnStderr: true
