# Define the trigger for the pipeline
trigger:
- main

# Define the agent pool
pool:
  name: 'my-personal-computer'

variables:
  - group: BuildVariables

# Define stages
stages:
- stage: Build
  jobs:
  - job: Build
    variables:
      build.clean: all
      platform: x64
      version: "current"
      appVersion: "1.0"
      appBuild: $[counter(variables['appVersion'], 0)]
      appRevision: 0
      createRuntimePackages: False
      skipComponentGovernanceDetection: True
    steps:
    - task: PowerShell@2
      displayName: 'Set Execution Policy'
      inputs:
        targetType: 'inline'
        script: |
          Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force

    - task: PowerShell@2
      displayName: 'Update Build Number'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.updatebuildnumber]$(appVersion).$(appBuild).$(appRevision)"
          
    - task: PowerPlatformToolInstaller@2
      displayName: 'Install Power Platform Tools'
      inputs:
        DefaultVersion: true

    - task: PowerPlatformExportSolution@2
      displayName: 'Export Power Platform Solution'
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'Source Connection'
        SolutionName: '$(SolutionName)'
        SolutionOutputFile: '$(Build.StagingDirectory)\$(SolutionName)_Unmanaged.zip'
        TargetVersion: '1.0.0.0'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        
    - task: PowerPlatformUnpackSolution@2
      displayName: 'Unpack Power Platform Solution'
      inputs:
        SolutionInputFile: '$(Build.StagingDirectory)\$(SolutionName)_Unmanaged.zip'
        SolutionTargetFolder: '$(Build.SourcesDirectory)\$(SolutionName)\Unmanaged'
        
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Unpacked Solution'
      inputs:
        PathtoPublish: '$(Build.SourcesDirectory)\$(SolutionName)\Unmanaged'
        ArtifactName: 'drop'
        publishLocation: 'Container'
